version: '3.5'
services:

  www:
    image: anchorfree/hugo:${BRANCH_NAME:-master}
    container_name: hugo
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HUGO_VERSION=0.53
    ports:
      - "1313:1313/tcp"
